### ISSUE TITLE
Need to be able to choose 1.0+ or 2.0+ etc.

### ISSUE THREAD

**Issue by raptureoh9** [opendreamnet/sukebezone#2]
Need to be able to configure the deepsukebe settings.

I tested a photo myself with 1.0+ and 2.0+ directly on deepsukebe, they both turned out pretty great although different.

I then tested the same exact photo through sukebezone and it turned out terrible (so I'm guessing maybe it's just picking regular "1.0" as the algorithm type?)

In sukebezone config we need to be able to choose 1.0+ or 2.0+ etc. as well as the 1024 resolution setting.

Preferably, I'd actually like to configure it to have every photo run through both 1.0+ and 2.0+ automatically.

**Comment by kolessios** [comment]
Thanks for the feedback, this option will be implemented in the next version and will be sent by email as soon as possible. 👍

**Comment by kolessios** [comment]
🎉 SukebeZone v2.2.0 now allows you to select the version or run it through the two "plus" versions for comparison. 

As an additional note, SukebeZone automatically handles the size of the photo so that it is always the largest possible (1024px).

**Comment by Sneydertr** [comment]
Thanks you
