### ISSUE TITLE
Referral

### ISSUE THREAD

**Issue by jack9119** [opendreamnet/sukebezone#7]
Referral for https://www.sukebezone.com not working keep showing this
![Screenshot_20210927-092030_Chrome](https://user-images.githubusercontent.com/91441994/134832242-c9374307-6960-4e4f-88a1-281a2db427ec.jpg)

**Comment by kolessios** [comment]
Hello, this is normal because as mentioned in the referral program description, we have a limit of 1000 quota and this has been depleted for this month. You will receive free quota again in October.
