### ISSUE TITLE
referrals not work

### ISSUE THREAD

**Issue by gost2580** [opendreamnet/sukebezone#8]
I wrote an email and submitted it, but it says "New users only". Also, if you submit another email, the login site? It seems to be sending a message, but nothing came through the email. I hope it gets resolved soon.
![Screenshot_20211002-111113_Chrome](https://user-images.githubusercontent.com/91767708/135700750-11c58a68-d872-46a1-948c-5d8ff5f40c25.png)

**Comment by kolessios** [comment]
The referral program is only for new users, once you register an email you can not register another one, please check that the email is not in the SPAM folder or try again another day.
